### ISSUE TITLE
Can't run Snake via Brickman

### ISSUE THREAD

**Issue by LegoMindstormsRobots** [donwojtallo/ev3dev-snake-js#1]
Hi,
I Can't seem to run Snake via the Brickman Browser. When I try the EV3 Brick locks-up requiring power removal to reset it.
I can run it via console without any issues.
I have followed your instructions to the letter.
That said, it's a great demo.

cheers

Ray
www.LegoMindstormsRobots.com

**Comment by donwojtallo** [comment]
Hi.
Thanks for pointing issue.
I will check this out tomorrow and try to fix that.

**Comment by donwojtallo** [comment]
I've found a problem I think. In the release the ioctl binary file is broken.
Please download this file: http://appsonline.pl/ioctl.node
and put this into 'node_modules/ioctl/build/Release/' (you have to override old file).
I've updated the release with this file (1.0.1).

**Comment by donwojtallo** [comment]
A month has passed. I assume that this problem is solved. Please reopen this issue if the problem still exists.
