### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by szq610** [donwojtallo/ev3dev-snake-js#2]
it said:
npm WARN package.json Snake@ No repository field.
npm WARN deprecated ev3dev@1.0.0: This package has been renamed to 'ev3dev-lang'. Please update your dependencies.

**Comment by donwojtallo** [comment]
Ok, thanks. I will update this soon :)

**Comment by donwojtallo** [comment]
Those messages are just warnings, and should not interrupt the installation. However, I've updated `package.json`. See https://github.com/donwojtallo/ev3dev-snake-js/commit/3f5a5aa39af4c89072cbc5c2efd3d6724433e305

There might be an another problem after last NodeJS updates. If you got trouble with compiling `ioctl` run this:
`sudo npm -g install npm node-gyp`
This might take a while.
I close this issue, please reopen this if still not working.
